- .github/workflows/main.yaml
Fixes #2.
CI includes `gofmt` and `go vet`.
> Basic CI setup based on GitHub actions.

- go.mod
Initialized the `go.mod` file.
> Initializing Go module

- .github/workflows/main.yaml
Following guidance from go/github-actions.
> Using tagged docker images instead of `-latest`

- tests/requestparsing/basicauth_test.go
- tests/requestparsing/contentlengthandtransferencoding_test.go
- tests/requestparsing/doc.go
- tests/requestparsing/header_test.go
- tests/requestparsing/host_test.go
- tests/requestparsing/referer_test.go
- tests/requestparsing/statusmessages.go
- tests/requestparsing/useragent_test.go
Forgot to add licensing information in #10.
> Adding license to header tests

- safehttp/handler.go
- safehttp/incoming_request.go
- safehttp/prototype.go
- safehttp/response_writer.go
- tests/integration/safehtml/safehtml_test.go
Created a dummy structure for safehttp.IncomingRequest and safehttp.ResponseWriter that integrates http.ResponseWriter and http.Request
> Initial skeleton for the safehttp library that integrates the net/http package

- safehttp/handler.go
- safehttp/incoming_request.go
- safehttp/prototype.go
- safehttp/response.go
- safehttp/response_writer.go
- safehttp/status.go
- tests/integration/safehtml/safehtml_test.go
In both #16 and #18 licensing was forgotten.
> Added license to safehttp skeleton

- README.md
- docs/high-level-design.md
Part of #9.
The design parts have been purposefully left out. We'll start adding these as we go.
> Added a document about goals.

- tests/formparams/form_params_test.go
Fixes:
- mistake in error output
- missing error checking when parsing forms
> Small fixes in the form parameters tests

- safehttp/header.go
- safehttp/header_test.go
- safehttp/incoming_request.go
- safehttp/prototype.go
- safehttp/response_writer.go
- tests/integration/header/header_test.go
- tests/integration/safehtml/safehtml_test.go
This PR implements the safe header type and fixes some left over comments from #18
> Safe header type

- tests/integration/safehtml/safehtml_test.go
Fixes #27 for `tests/integration/safehtml/safehtml_test.go`
> Removed reliance on httptest.ResponseRecorder in test

- .github/workflows/main.yaml
Apparently, gofmt doesn't set an exit status.
https://twitter.com/zekjur/status/1289463636331646977
> Fixes the gofmt GitHub action according to Michael's tweet ;)

- safehttp/form.go
- safehttp/form_test.go
- safehttp/incoming_request.go
- tests/formparams/form_params_test.go
Fixes #19 
Created the initial  structure of safehttp.Form with some preliminary tests
> Initial structure of the safe form type

- tests/integration/header/header_test.go
- tests/integration/safehtml/safehtml_test.go
Based on feedback in other PRs `dispatcher` and `responseWriter` should be renamed `testDispatcher` and `responseRecorder` in test files for consistency.
> Renamed dispatcher and responsewriter for consistency

- safehttp/form.go
- safehttp/form_test.go
> Changed to use strconv.ParseBool

- safehttp/form_test.go
Fixes #43 
Refactored parts of the form tests to make them less complex and bug-prone.
> Form tests cleanup

- safehttp/mux.go
- safehttp/plugins/csp/csp_test.go
- safehttp/status.go
Fixes #112, #113 
Added the HTTP methods and status codes as well as their RFC sections.
> Added all the HTTP methods and status codes present in the net/http library

- safehttp/mux.go
- safehttp/mux_test.go
- safehttp/plugins/collector/collector.go
- safehttp/plugins/fetch_metadata/fetch_metadata.go
- safehttp/plugins/hsts/hsts.go
- safehttp/plugins/xsrf/xsrf.go
- safehttp/response_writer.go
- safehttp/response_writer_test.go
> Replaced ClientError and ServerError with WriteError in ResponseWriter

- safehttp/handler.go
> Removed unused safehttp.HandleFunc

- safehttp/plugins/fetch_metadata/fetch_metadata.go
- safehttp/plugins/xsrf/xsrf.go
- tests/formparams/form_params_test.go
- tests/queryparams/query_params_test.go
Improves the documentation of the project (#132) by adding the remaining package level comments to:
* safehttp/plugins/xsrf
* safehttp/plugins/fetch_metadata
> Add remaining package level godocs

- safehttp/plugins/fetch_metadata/fetch_metadata_test.go
- safehttp/plugins/hsts/hsts_test.go
- safehttp/plugins/xsrf/xsrf_test.go
- safehttp/response_writer_test.go
- tests/integration/header/header_test.go
- tests/integration/hsts/hsts_test.go
- tests/integration/mux/mux_test.go
- tests/integration/staticheaders/staticheaders_test.go
> Cleanup some inconsistencies in the test error message, variable names and rename the safemux_test package to mux_test

- safehttp/plugins/coop/coop.go
- safehttp/plugins/coop/coop_test.go
> Added COOP implementation.

- safehttp/plugins/coop/coop.go
As discussed with @kele this provides better separation between data and code.
> coop: internal refactor

- safesql/safesql.go
- safesql/sqlwrap.go
- safesql/sqlwrap_go1_15.go
safesql docs didn't display correctly and were incomplete.
> safesql: fix doc

- safehttp/plugins/xsrf/html/xsrf.go
- safehttp/plugins/xsrf/html/xsrf_test.go
- tests/integration/xsrf/xsrf_test.go
The `Before` stage now only retrieves and validates the XSRF token, in case of state-changing requests. This way, we don't need to add the token to the `safehttp.IncomingRequest` context anymore.
> Moved token generation to the Commit phase for xsrfhtml

- safehttp/mux.go
As part of that change, `ServeMuxConfig` took the responsibility of
creating method handlers and registering them.
The `ServeMux` stays as it is for now, as I expect that we will like to add inspection capabilities for conformance checks soon. But this simplification is mostly to make `ResponseWriter` refactoring easier.
> Simplified request handling by removing the standardHandler.

- safehttp/mux.go
- safehttp/mux_test.go
> Fix Handler registering mixup.

- examples/echo/echo.go
- examples/echo/security/web/web.go
> Example echo server

- examples/echo/security/web/web.go
- safehttp/defaults/defaults.go
- safehttp/defaults/defaults_test.go
- safehttp/plugins/fetchmetadata/fetchmetadata.go
- safehttp/plugins/fetchmetadata/fetchmetadata_test.go
- safehttp/plugins/staticheaders/staticheaders.go
For now it contains just a factory for safe ServeMuxConfigs.
> Added a `defaults` package.

- internal/requesttesting/test_harness.go
- safehttp/server.go
- safehttp/server_test.go
This allows to construct a ready-to use and safe server from a Mux and an address
> Add a Server type

- safehttp/plugins/csp/csp.go
- safehttp/plugins/csp/csp_test.go
- tests/integration/csp/csp_test.go
This is the first step to add a full support for framing protection (described in #77)
> It's a good idea to open an issue first for discussion.
> Extend FramingPolicy to include allowed sources.

- safehttp/doc.go
> First draft of safehttp godoc comments.

- safehttp/default_dispatcher_test.go
- safehttp/fileserver_test.go
- safehttp/flight_test.go
- safehttp/mux_test.go
- safehttp/plugins/hostcheck/hostcheck_test.go
- safehttp/safehttptest/recorder.go
- safehttp/task_test.go
- tests/integration/csp/csp_test.go
- tests/integration/errors/errors_test.go
- tests/integration/header/header_test.go
- tests/integration/hsts/hsts_test.go
- tests/integration/mux/mux_test.go
- tests/integration/safehtml/safehtml_test.go
- tests/integration/staticheaders/staticheaders_test.go
- tests/integration/xsrf/xsrf_test.go
Removed the`safehttptest.TestResponseWriter` and all its usages.
> Remove safehttptest.TestResponseWriter

- safehttp/form.go
- safehttp/form_test.go
- safehttp/incoming_request.go
> Sanitise file names in multipart forms.

- safehttp/fileserver_1_16_test.go
- safehttp/plugins/htmlinject/embed_1_16.go
- safehttp/plugins/htmlinject/embed_1_16_test.go
This also fixes a broken test from the previous pr.
> Add support for embedfs to htmlinject.

- safehttp/mux.go
- safehttp/mux_test.go
> MethodNotAllowed errors now go through ResponseWriter.WriteError

- safehttp/default_dispatcher.go
- safehttp/default_dispatcher_test.go
- safehttp/flight.go
- safehttp/flight_test.go
- safehttp/plugins/fetchmetadata/fetchmetadata.go
- safehttp/plugins/fetchmetadata/fetchmetadata_test.go
- safehttp/plugins/hsts/hsts.go
- safehttp/plugins/hsts/hsts_test.go
- safehttp/response.go
- safehttp/response_writer.go
- safehttp/safehttptest/recorder.go
This fixes a bug that caused Redirect to not run Commit phase.
> Turn redirects into responses.

- safehttp/default_dispatcher.go
- safehttp/default_dispatcher_test.go
- safehttp/flight.go
- safehttp/flight_test.go
- safehttp/plugins/collector/collector.go
- safehttp/plugins/cors/cors.go
- safehttp/response.go
- safehttp/response_writer.go
Support NoContent as a normal Response.
> Remove NoContent special-casing.

- examples/echo/security/web/web.go
- examples/sample-application/secure/mux.go
- safehttp/defaults/defaults.go
- safehttp/plugins/fetchmetadata/fetchmetadata.go
- safehttp/plugins/fetchmetadata/fetchmetadata_test.go
> fetchmetadata: Update to new API.

- safehttp/plugins/reportingapi/reporting.go
- safehttp/plugins/reportingapi/reporting_test.go
> Add report-to plugin.

- safehttp/interceptor.go
- safehttp/mux.go
- safehttp/mux_test.go
> Add support for wrapped interceptor, detect config clashes.

- safehttp/mux.go
This PR also updates the Intercept doc to add the order guarantee.
> Make Intercept variadic to better support orchestration.

- examples/echo/echo.go
- examples/echo/security/web/web.go
- examples/sample-application/cmd/main.go
- examples/sample-application/server/server.go
- examples/trustedtypes/server.go
- safehttp/defaults/defaults_test.go
- safehttp/fileserver_1_16_test.go
- safehttp/fileserver_test.go
- safehttp/flight_test.go
- safehttp/flightvalues_test.go
- safehttp/migration.go
- safehttp/migration_test.go
- safehttp/mux.go
- safehttp/mux_test.go
- safehttp/plugins/hostcheck/hostcheck_test.go
- safehttp/server_test.go
- tests/integration/csp/csp_test.go
- tests/integration/devmode/devmode_test.go
- tests/integration/devmodefreeze/devmodefreeze_test.go
- tests/integration/errors/errors_test.go
- tests/integration/header/header_test.go
- tests/integration/hsts/hsts_test.go
- tests/integration/mux/mux_test.go
- tests/integration/safehtml/safehtml_test.go
- tests/integration/staticheaders/staticheaders_test.go
- tests/integration/xsrf/xsrf_test.go
Functional changes are inside safehttp/mux.go.
> Removed ServeMuxConfig.Handle in favor of ServeMux.Handle to be more consistent with net/http

- cmd/bancheck/doc.go
- safehttp/doc.go
Adding both high level and a bit more detailed documentation of the bancheck linter.
> Add bancheck documentation

- examples/sample-application/cmd/main.go
- examples/sample-application/secure/auth/auth.go
- examples/sample-application/secure/auth/ctx.go
- examples/sample-application/secure/dispatcher.go
- examples/sample-application/secure/docs.go
- examples/sample-application/secure/mux.go
- examples/sample-application/secure/responses/errors.go
- examples/sample-application/secure/templates/embed.go
- examples/sample-application/server/server.go
- examples/sample-application/storage/fakedb.go
- safehttp/fileserver_1_16.go
- safehttp/fileserver_1_16_test.go
- safehttp/plugins/htmlinject/embed_1_16.go
- safehttp/plugins/htmlinject/embed_1_16_test.go
- safesql/sqlwrap_go1_15.go
Running gofmt adds these "new-style" build tags now. This is what
has caused CI to be red.
> all: update build tags

- safehttp/defaults/defaults_test.go
- tests/integration/devmode/devmode_test.go
- tests/integration/devmodefreeze/devmodefreeze_test.go
> chore: use bytes.Equal
