google/go-safeweb

testing/requesttesting/test_harness.go

The change was done to simplify importing the package when writing tests as otherwise it would have coincided with the `testing` package in the standard library.

Renamed the package that contains the test harness requesttesting

---

go.mod
go.sum
tests/requestparsing/README.md
tests/requestparsing/basicauth_test.go
tests/requestparsing/contentlengthandtransferencoding_test.go
tests/requestparsing/doc.go
tests/requestparsing/header_test.go
tests/requestparsing/host_test.go
tests/requestparsing/referer_test.go
tests/requestparsing/statusmessages.go
tests/requestparsing/useragent_test.go

Fixes #5 
Includes many different tests.

Header parsing tests

---

go.mod
go.sum
safehttp/handler.go
safehttp/incoming_request.go
safehttp/prototype.go
safehttp/response.go
safehttp/response_writer.go
safehttp/status.go
tests/integration/safehtml/safehtml_test.go

This is a very early prototype. Anything can change.
`Machinery` is introduced to avoid designing the whole package at once. All things related to registering handlers, muxing, registering safe responses etc is right now hidden there.

First draft of the core of safehttp.

---

internal/requesttesting/test_harness.go
testing/README.md
tests/formparams/form_params_test.go
tests/headers/basicauth_test.go
tests/headers/clte_test.go
tests/headers/doc.go
tests/headers/header_test.go
tests/headers/host_test.go
tests/headers/referer_test.go
tests/headers/statusmessages.go
tests/headers/useragent_test.go
tests/queryparams/query_params_test.go

We talked about moving the test harness to the `internal` folder to avoid having both a `testing` package and a `tests` package. We also didn't want the test harness to be importable when using the `safehttp` package.

Moved test harness to internal

---

tests/headers/header_test.go

A question came up in #21 whether the `http.Header.Values()` function sorts the resulting string slice somehow. I added a test to verify that the current behavior is to order the slice in the same order as the headers were sent from the client.

Added test for ordering of http.Header.Values()

---

tests/integration/header/header_test.go
tests/integration/safehtml/safehtml_test.go

Addresses #27 for tests in `tests/integration/header/header_test.go`.

Remove use of httptest.ResponseRecorder in header tests

---

tests/headers/basicauth_test.go
tests/headers/clte_test.go
tests/headers/header_test.go
tests/headers/host_test.go
tests/headers/referer_test.go
tests/headers/useragent_test.go

Adresses #23 for the header tests.
All of the tests that show strange or undesirable behavior have now been more clearly documented.

Clearly document strange header parsing behavior

---

safehttp/dispatcher_test.go
safehttp/form_test.go
safehttp/recorder_dispatcher_test.go

Fixes #27 in `/safehttp/form_test.go`.

Remove httptest.ResponseRecorder in form test

---

safehttp/handler.go
safehttp/incoming_request.go
safehttp/mux.go
safehttp/mux_test.go
safehttp/prototype.go

`safehttp.ServeMux` is a wrapper around the `http.ServeMux`. Currently, it supports registering based on methods and specifying the list of allowed domains.
Co-authored-by: mattiasgrenfeldt <grenfeldt@google.com>
Co-authored-by: mihalimara22 <maramihali@google.com>

Skeleton for safe multiplexer.

---

safehttp/incoming_request.go
safehttp/plugins/hsts/hsts.go
safehttp/plugins/hsts/hsts_test.go
safehttp/response_writer.go
safehttp/status.go

A plugin which automatically applies HSTS to incoming requests. The `Before` function must be run on incoming requests before they are passed to a handler.

HSTS plugin skeleton

---

safehttp/header.go
safehttp/header_test.go
safehttp/plugins/hsts/hsts.go
safehttp/plugins/hsts/hsts_test.go

Fixes #44
Plugins might need to mark a header as immutable and then change it at a later stage. A method called Claim will therefore be implemented that sets the header as immutable and returns something that can later change the header. When Claim is implemented there will be no need for MarkImmutable (for now) and therefore it will be removed.

Header Claiming

---

safehttp/plugins/hsts/hsts.go
safehttp/plugins/hsts/hsts_test.go
safehttp/response_writer.go

Fixes #40 
`safehttp.ResponseWriter.ServerError` currently has the following signature:
```go
func (w *ResponseWriter) ServerError(code StatusCode, resp Response) Result
```
It takes a `safehttp.Response` as an argument, but there might be places where we want to respond with a server error without having the ability to create safe responses. For example if a plugin needs to interrupt the handling of an incoming request. We have therefore decided that **for now** `Response` should be removed from the `ServerError` signature.

Removed Response from ServerError

---

safehttp/response_writer.go

Fixes #52 .
Adds functionality to the `safehttp.ResponseWriter` so that a response with the `4xx` status code can be returned when the request fails because of a client error.

ResponeWriter.ClientError support

---

safehttp/incoming_request.go
safehttp/mux.go
safehttp/plugins/hsts/hsts_test.go
safehttp/prototype.go
safehttp/response_writer.go
safehttp/safehttptest/recorder.go
safehttp/safehttptest/request.go

Fixes #46 
We implemented a test helper package to use when testing plugins. It uses the `httptest` package internally.

Introduced the safehttptest to aid end-to-end testing

---

docs/high-level-design.md
docs/plugins.md
docs/plugins/hsts.md
safehttp/plugins/hsts/hsts.go

Fixes #51 
Documentation for the HSTS plugin has been added. Also added a `plugins.md` file which can be used to describe plugins more in the future. `plugins.md` also contains a list of all the plugins we have currently implemented.
I also updated a godoc comment in the `hsts.Plugin` struct.
The links will point to the right place once this is merged.

Added HSTS plugin documentation and structure for adding documentation about other plugins in the future.

---

internal/requesttesting/test_harness.go

Fixes #59 
Added a call to `runtime.Gosched()` before the call to `server.Shutdown()`.
This dramatically improved the time it took to run the tests. It turns out that `server.Shutdown` polls every 0.5 s if all idle connections are closed. When we call server.Shutdown, our connection isn't closed just yet, so therefore we always have to wait 0.5 s for each test. But in reality it takes a lot less time than 0.5 s for the connection to finish closing. So if we just give up execution for a moment before calling `server.Shutdown` then the other goroutines have the time to shut the connection down before `server.Shutdown` checks if everything is closed. And then we don't get punished with waiting for 0.5 s every time we try to shut down.
With this approach sometimes tests still take 0.5 s to …

Improved speed of the test harness for testing net/http parsing by adding a call to runtime.Gosched() before shutting down the server

---

safehttp/incoming_request.go
safehttp/url.go
safehttp/url_test.go

Fixes #33
A new `safehttp.URL` type is implemented. It is very similar to the `net/url.URL` type. 
You can now access URL query parameters by using the `safehttp.URL.Query` method which returns a `safehttp.Form` containing the values.
`net/url.URL` contains a lot more functionality than `safehttp.URL`. The rest of the functionality can be implemented later as needed.

Implementing safehttp.URL type and a way of accessing URL query parameters

---

go.sum
safehttp/interceptor.go
safehttp/mux.go
safehttp/mux_test.go
safehttp/prototype.go
safehttp/recorder_dispatcher_test.go
safehttp/response_writer.go
safehttp/safehttptest/recorder.go

Fixes #64 
Implemented the interceptors infrastructure that supports adding interceptors for `ServeMux`. To install an interceptor, the user needs to pass it to one of the installation functions, together with a key that will uniquely identify the interceptor and that the user will need to keep track of.  The `Interceptor.Before` function will run prior to accessing a handler for all the interceptors installed. Within the handler, interaction with an interceptor is possible by calling the `Interceptor()` getter function on the `ResponseWriter` and passing the interceptor key as a parameter to the function.

Interceptors Infrastructure

---

safehttp/cookie.go
safehttp/cookie_test.go
safehttp/header.go
safehttp/header_test.go
safehttp/incoming_request.go
safehttp/incoming_request_test.go
safehttp/response_writer.go
safehttp/response_writer_test.go

Fixes #56 
This PR implements a cookie type with safe default values.
It also implements cookie reading methods on `IncomingRequest` and cookie setting methods on `ResponseWriter`. This mimics the setters and getters available for cookies in `net/http`.
The `safehttp.Header.SetCookie` method has been removed. Now, cookie interactions only happen with the `ResponseWriter` and the `IncomingRequest`  and never with the `Header` directly.

Implemented a safehttp.Cookie type, made it readable from IncomingRequest and settable from ResponseWriter.

---

safehttp/plugins/hsts/hsts.go
tests/integration/hsts/hsts_test.go

Fixes #68 
Now that there is plugin infrastructure in the `ServeMux` there should be integration tests with the HSTS plugin.

Added integration test which installs the HSTS plugin on a ServeMux and serves a request.

---

safehttp/incoming_request.go
safehttp/incoming_request_test.go

Fixes #70 
Extended the `safehttp.IncomingRequest` API to add functions for getting and setting the context of the underlying `http.Request` as well as tests.

Added functions for retrieving the context.Context and changing it for a safehttp.IncomingRequest

---

.github/workflows/copyright_linter.sh
.github/workflows/main.yaml
.github/workflows/source-code-copyright-header.txt
tests/formparams/form_params_test.go

Fixes #81 
We have forgotten to put the copyright notice in a couple of PRs. Now this won't happen.

Added copyright linter to CI so that we don't forget copyright information at the top of source files.

---

docs/plugins.md
docs/plugins/hsts.md
docs/plugins/staticheaders.md
safehttp/plugins/staticheaders/staticheaders.go
safehttp/plugins/staticheaders/staticheaders_test.go
tests/integration/staticheaders/staticheaders_test.go

Fixes #80 
This plugin sets
```
X-Content-Type-Options: nosniff
X-XSS-Protection: 0
```
on all outgoing responses.
There is currently no way to disable setting these headers.

Static security header plugin added which sets XCTO and XXP.

---

safesql/internal/raw/raw.go
safesql/legacyconversions/legacyconversions.go
safesql/safesql.go
safesql/safesql_test.go
safesql/sqlwrap.go
safesql/uncheckedconversions/uncheckedconversions.go

This implementation does not yet provide `FromIdentifierComponents` and `FromQuotedIdentifierComponents` as they are SQL-dialect dependent and there seems to not be a good way to create a generic helper for them.
If the need for them arises I'll try to work some magic to implement something that provides a similar functionality.

safesql: Add first implementation.

---

tests/headers/clte_test.go

As of Go 1.15 `Transfer-Encoding: identity` has been removed. Therefore we need to update our header parsing tests to reflect that.

Updating tests to reflect that TE identity has been removed in Go1.15

---

safehttp/plugins/hsts/hsts_test.go
safehttp/plugins/staticheaders/staticheaders_test.go
safehttp/plugins/xsrf/xsrf_test.go
safehttp/safehttptest/recorder.go

Fixes #105 
This is so that we can use the `safehttp.StatusXxxx` constants instead of number literals in tests without having to cast the constants from `safehttp.StatusCode` to `int` in every test we write that uses `safehttptest`.

Changed safehttptest.ResponseRecorder.Status() to return a safehttp.StatusCode instead of an int.

---

safehttp/header.go
safehttp/interceptor.go
safehttp/mux.go
safehttp/mux_test.go
safehttp/plugins/csp/csp.go
safehttp/plugins/csp/csp_test.go

It supports creating custom CSP policies. The interceptor contains two policies, one for enforcement and one for reporting. A default policy based on https://csp.withgoogle.com/docs/strict-csp.html is also provided.
Fixes #74

Added first version of CSP plugin.

---

safehttp/plugins/csp/csp_test.go

Fixed commit #5c6aabe that is causing `go vet` and `go test` to fail because of a type mismatich (`int` to `safehttp.StatusCode` comparison in the CSP tests).

Removed casting in CSP tests that is breaking master

---

safehttp/form_test.go
safehttp/handler.go
safehttp/interceptor.go
safehttp/mux.go
safehttp/mux_test.go
safehttp/plugins/csp/csp.go
safehttp/plugins/hsts/hsts.go
safehttp/plugins/staticheaders/staticheaders.go
safehttp/plugins/xsrf/xsrf.go
safehttp/response_writer.go
safehttp/response_writer_test.go
safehttp/safehttptest/recorder.go
tests/integration/header/header_test.go
tests/integration/hsts/hsts_test.go
tests/integration/safehtml/safehtml_test.go
tests/integration/staticheaders/staticheaders_test.go

Fixes #97 
To be able to store the state whether or not the `ResponseWriter` was written to or not the signature of `Handler` and `Interceptor.Before` had to change to accept a `*ResponseWriter` instead of a `ResponseWriter`. This needed to be changed in **a lot** of places.

Make sure that ResponseWriter is only written to once, otherwise panic.

---

safehttp/form_test.go
safehttp/incoming_request.go
safehttp/incoming_request_test.go
safehttp/mux_test.go
safehttp/plugins/hsts/hsts_test.go
safehttp/plugins/xsrf/xsrf_test.go
safehttp/recorder_dispatcher_test.go
tests/integration/header/header_test.go
tests/integration/hsts/hsts_test.go
tests/integration/safehtml/safehtml_test.go
tests/integration/staticheaders/staticheaders_test.go

Now we use safehttp.MethodXxxx and safehttp.StatusXxxx everywhere instead of strings and ints

---

safehttp/plugins/csp/csp.go
safehttp/plugins/csp/csp_test.go

Fixes #111 
You can now specify a set of hashes in the CSP plugin. An example of such a hash is `sha256-CihokcEcBW4atb/CW/XWsvWwbTjqwQlE9nj9ii5ww5M=`

Added set of hashes to CSP plugin

---

go.sum
safehttp/incoming_request.go
safehttp/plugins/fetch_metadata/fetch_metadata.go
safehttp/plugins/fetch_metadata/fetch_metadata_test.go
safehttp/url.go
safehttp/url_test.go

Fixes #78 
Implemented the initial version of Fetch Metadata plugin. It enforces a Resource Isolation Policy by default and supports enabling and disabling a Navigation Isolation Policy. The user can provide a custom policy instead of the default policy if needed. It also supports switching to a reporting mode that allows all requests to pass and only logs violation.

Fetch Metadata Plugin Implementation

---

safehttp/config.go
safehttp/interceptor.go
safehttp/mux.go
safehttp/mux_test.go
safehttp/plugins/hsts/hsts.go
safehttp/plugins/hsts/hsts_test.go
safehttp/plugins/staticheaders/staticheaders.go
safehttp/plugins/staticheaders/staticheaders_test.go
safehttp/plugins/xsrf/xsrf.go
safehttp/plugins/xsrf/xsrf_test.go
tests/integration/hsts/hsts_test.go
tests/integration/staticheaders/staticheaders_test.go

Fixes #87 
Added interceptor configurations that enable the user to modify the behaviour of interceptors per handler. Interceptors need to be installed before registering handlers otherwise the interceptor won't take effect. The configuration type is expected to be implemented for every interceptor that is configurable.

Per handler interceptor configurations

---

safehttp/form_test.go
safehttp/mux.go
safehttp/mux_test.go
safehttp/plugins/hsts/hsts.go
safehttp/plugins/staticheaders/staticheaders.go
safehttp/plugins/xsrf/xsrf.go
safehttp/response_writer.go
safehttp/response_writer_test.go

Fixes #109 
I added a `safehttp.NotWritten` variable which we can use everywhere instead of `safehttp.Result{}`. If a `Handler` returns `NotWritten` then a `204 No Content` response is automatically set by the ServeMux.

Added a safehttp.NotWritten result so that safehttp.Result{} can stop being used.

---

go.sum
safehttp/incoming_request.go
safehttp/plugins/xsrf/xsrf.go
safehttp/plugins/xsrf/xsrf_test.go

Fixes #122 
Extended the XSRF plugin to support token generation in the `xsrf.Before()` function. This will then be added to the context of a `safehttp.IncomingRequest` and can be retrieved using the `xsrf.Token()` getter.

Added token generation to the XSRF plugin.

---

safehttp/form.go
safehttp/form_test.go
safehttp/incoming_request.go
safehttp/incoming_request_test.go

Fixes #32, #38
Extended the `MultipartForm` to support retrieving file uploads from incoming requests. This will prevent the user from directly accessing the multipart form but will still allow access to the accessor methods in `multipart` used for opening files.
Fixed the issue that was causing a multipart form to be capped at 32 MB (my misunderstanding of documentation).
This branch  is rebased on top of `grenfeldt-splitting-form-tests` branch  (#125 ).

Extended the MultipartForm type to allow accessing file uploads

---

safehttp/mux.go
safehttp/mux_test.go
safehttp/response_writer.go
safehttp/response_writer_test.go
safehttp/safehttptest/recorder.go
tests/integration/hsts/hsts_test.go
tests/integration/staticheaders/staticheaders_test.go

Now Interceptors are stored together with their configs in slices instead of maps. To interact with an interceptor from the handler that interceptor needs to implement package level functions which take ResponseWriters and IncomingRequests and do things. State can be stored in the context of the request.
Fixes #143

Removed Interceptor keys from ServeMux, now interceptors and their configs are stored in a slice.

---

safehttp/plugins/xsrf/xsrf.go
safehttp/plugins/xsrf/xsrf_test.go

Fixes #130, #136 
The XSRF protection can now also protect login forms by setting a custom cookie to distinguish between users. The cookie will then be used as an identifier in the verification and generation algorithm.

Added pre-login XSRF protection to the XSRF plugin

---

safehttp/plugins/csp/csp.go
safehttp/plugins/csp/csp_test.go

Previously, `Policy` would contain a single function field. This made
it impossible to inspect the configuration of a given `Policy` object.
Now, `Policy` is an interface implemented by `StrictPolicy` (replaced
`StrictCSPBuilder`) and `FramingPolicy` (replaced `FramingPolicyBuilder`).
The package can now look at the Interceptor and make checks like:
```
if s := Interceptor.Enforce[0].(StrictPolicy); s.UnsafeEval {
panic("unsafe-eval is dangerous!")
}
```
This enables implementing a conformance check in the nearest future
(a feature coming soon).

CSP plugin refactoring allowing Interceptor inspection.

---

safehttp/interceptor.go
safehttp/mux.go
safehttp/mux_test.go
safehttp/plugins/csp/csp.go
safehttp/plugins/fetch_metadata/fetch_metadata.go
safehttp/plugins/hsts/hsts.go
safehttp/plugins/staticheaders/staticheaders.go
safehttp/plugins/xsrf/xsrf.go
safehttp/response.go
safehttp/response_writer.go
safehttp/response_writer_test.go
safehttp/safehttptest/recorder.go

Fixes #145
Added the `Commit` phase to the Interceptor interface. This will be called by the `safehttp.ResponseWriter` before a response is written to the underlying `http.ResponseWriter`, for all interceptors that were installed on the handler. If a response  is written in any of the `Commit` phases,  then the `Commit` phases of the remaining interceptor won't execute.
As the `Commit` phase takes a `safehttp.Response` as argument (e.g. for injecting nonces), we also created a `safehttp.TemplateResponse` interface that encapsulates a safe template and the data that is applied to it.
Co-authored-by: Mihali Mara <maramihali@google.com>

Added the Commit phase

---

safehttp/plugins/collector/collector.go
safehttp/plugins/cors/cors.go
safehttp/plugins/csp/csp.go
safehttp/plugins/hsts/hsts.go
safehttp/plugins/staticheaders/staticheaders.go
safehttp/safehttptest/doc.go

As part of improving the documentation of the project ( #132 ) I've added package level godocs for the following packages:
- safehttp/plugins/collector
- safehttp/plugins/cors
- safehttp/plugins/csp
- safehttp/plugins/hsts
- safehttp/plugins/staticheaders
- safehttp/safehttptest
Package level comments left to write are for:
- safehttp/plugins/xsrf
- safehttp/plugins/fetch_metadata
I'll let @maramihali write those since she wrote those packages.

Added package level godocs to Collector, CORS, CSP, HSTS, staticheaders and safehttptest.

---

safehttp/cookie.go
safehttp/handler.go
safehttp/incoming_request.go
safehttp/mux.go
safehttp/response.go
safehttp/response_writer.go

Fixes #132 
Completed the documentation in the repository. The TODOs left in `response_writer.go` will be fixed when #147 is merged. Comments related to error handling will be refactored when we handle `ResponseWriter.Write` and `Dispatcher` panics properly.

Completed the framework's godoc

---

safehttp/default_dispatcher.go
safehttp/default_dispatcher_test.go
safehttp/mux.go
safehttp/mux_test.go
safehttp/recorder_dispatcher_test.go
safehttp/response.go
safehttp/response_writer.go
safehttp/response_writer_test.go
safehttp/safehttptest/recorder.go
tests/integration/header/header_test.go
tests/integration/hsts/hsts_test.go
tests/integration/mux/mux_test.go
tests/integration/safehtml/safehtml_test.go
tests/integration/staticheaders/staticheaders_test.go

Fixes #60, #133
Extended the Dispatcher interface to support writing JSON safe responses and retrieving the Content-Type of safe response and added a . This way the ResponseWriter can query the Dispatcher to retrieve and set the Content-Type of a safe response before writing the response. Implemented and write tests for a default safe dispatcher.

Extended the Dispatcher interface to support writing JSON and retrieving the response Content-Type and created a safe default Dispatcher.

---

safehttp/cookie.go
safehttp/doc.go
safehttp/incoming_request_test.go
safehttp/mux.go
safehttp/plugins/htmlinject/htmlinject_test.go
safehttp/status.go

The following changes have been done to address linters comments:
* Added missing documentation
* Replaced usage of `html/template` 
* ensure a `nil` context is not passed to a function directly
TODOS:
* Add godocs to `safesql/sqlwrap.go`.
* Add package level documentation in `safehttp/doc.go` to remove the TODO.

Address linter comments in the safehttp package

---

safehttp/plugins/cors/cors.go
safehttp/plugins/cors/cors_test.go
safehttp/plugins/csp/csp.go
safehttp/plugins/csp/csp_test.go
safehttp/plugins/fetch_metadata/fetch_metadata.go
safehttp/plugins/fetch_metadata/fetch_metadata_test.go
safehttp/plugins/hsts/hsts.go
safehttp/plugins/staticheaders/staticheaders.go
safehttp/plugins/xsrf/xsrf.go

Fixes #169 
Fixed by adding type assertion in each interceptor package like this:
```go
var _ safehttp.Interceptor = Interceptor{}
```

Ensure that all interceptors fullfill the safehttp.Interceptor interface

---

safehttp/mux_test.go
safehttp/plugins/cors/cors.go
safehttp/plugins/csp/csp.go
safehttp/plugins/fetch_metadata/fetch_metadata.go
safehttp/plugins/hsts/hsts.go
safehttp/plugins/staticheaders/staticheaders.go
safehttp/plugins/xsrf/xsrf.go

Repository cleanup to only have `safehttp.NotWritten()` as return value not also `safehttp.Result{}`.

Replace safehttp.Result{} with safehttp.NotWritten() in the repository

---

safehttp/response_writer.go

Set the Content-Type header before calling WriteHeader in the safehttp.ResponseWriter

---

tests/formparams/form_params_test.go
tests/queryparams/query_params_test.go

Renamed the initial form parameters and query parameters test packages so they build when using Google internal tooling conventions. Otherwise, the build rules generated by running `glaze` will result in errors. This changes do not affect building the packages in the open-source.

Rename the package name of the initial form parameters and query parameters test

---

safehttp/default_dispatcher.go
safehttp/default_dispatcher_test.go
safehttp/plugins/csp/csp.go
safehttp/plugins/csp/csp_test.go
safehttp/plugins/xsrf/xsrf.go
safehttp/plugins/xsrf/xsrf_test.go
safehttp/response.go
safehttp/response_writer.go
tests/integration/csp/csp_test.go
tests/integration/mux/mux_test.go
tests/integration/xsrf/xsrf_test.go

Fixes #76 
Extended the `safehttp.TemplateResponse` to support adding elements to a function map. This will be executed before the template is parsed. The CSP nonce and XSRF Token values will be added to this map in the `xsrf.Commit` and `csp.Commit` phases.

Implemented the Commit phase in the CSP and XSRF plugins

---

safehttp/mux.go
safehttp/mux_test.go
safehttp/plugins/hostcheck/hostcheck.go
safehttp/plugins/hostcheck/hostcheck_test.go
tests/integration/csp/csp_test.go
tests/integration/header/header_test.go
tests/integration/hsts/hsts_test.go
tests/integration/mux/mux_test.go
tests/integration/safehtml/safehtml_test.go
tests/integration/staticheaders/staticheaders_test.go
tests/integration/xsrf/xsrf_test.go

Host checks were performed inside the mux to protect from DNS rebinding
and HTTP request smuggling attacks. There is no real reason why these
should be inside the mux implementation instead of a plugin.
Fixes #168.

Host checks are now inside a hostcheck plugin.

---

safehttp/mux.go
safehttp/mux_test.go
safehttp/plugins/hostcheck/hostcheck_test.go
tests/integration/csp/csp_test.go
tests/integration/header/header_test.go
tests/integration/hsts/hsts_test.go
tests/integration/mux/mux_test.go
tests/integration/safehtml/safehtml_test.go
tests/integration/staticheaders/staticheaders_test.go
tests/integration/xsrf/xsrf_test.go

Related issues: #117, #88.
This is the first draft of a `ServeMuxBuilder`. Right now it's just a thin wrapper that contains virtually no logic.
In the nearest future, `ServeMux` will be simplified and some of the logic will be moved into `ServeMuxBuilder` instead.

Introducing ServeMuxBuilder

---

safehttp/mux.go
safehttp/mux_test.go
safehttp/plugins/hostcheck/hostcheck_test.go
tests/integration/csp/csp_test.go
tests/integration/header/header_test.go
tests/integration/hsts/hsts_test.go
tests/integration/mux/mux_test.go
tests/integration/safehtml/safehtml_test.go
tests/integration/staticheaders/staticheaders_test.go
tests/integration/xsrf/xsrf_test.go

`ServeMuxBuilder` is now `ServeMuxConfig`, and the API has telling names (e.g. `Build` is now a getter for the current `Mux`).

Improved naming for ServeMuxBuilder to make it more clear.

---

safehttp/plugins/htmlinject/htmlinject.go
safehttp/plugins/htmlinject/htmlinject_test.go

It was previously hard and brittle to use htmlinject as some constants were not exported (the ones to use as map keys in funcmap).
Moreover we were not noncing syles because our CSP plugin does not set the style-src directive, but users might want to use a different, stricter, CSP implementation.

htmlinject: added rule for styles and exported useful constants.

---

safehttp/plugins/htmlinject/htmlinject.go
safehttp/plugins/htmlinject/htmlinject_test.go
safehttp/plugins/htmlinject/testdata/first.tpl
safehttp/plugins/htmlinject/testdata/first.want
safehttp/plugins/htmlinject/testdata/second.tpl
safehttp/plugins/htmlinject/testdata/second.want

It was previously impossible to use htmlinject together with safehtml without an uncheckedconversion.
Depends on PR #197 
Fixes #173

htmlinject: provide helpers to load safehtml.Templates

---

safehttp/interceptor.go
safehttp/mux.go
safehttp/mux_test.go
safehttp/plugins/coop/coop.go
safehttp/plugins/cors/cors.go
safehttp/plugins/csp/csp.go
safehttp/plugins/fetch_metadata/fetch_metadata.go
safehttp/plugins/hostcheck/hostcheck.go
safehttp/plugins/hsts/hsts.go
safehttp/plugins/staticheaders/staticheaders.go
safehttp/plugins/xsrf/xsrf.go
safehttp/response.go
safehttp/response_writer.go

Fixes #201 
The `OnError` method of all interceptors associated with a handler will be called in `safehttp.ResponseWriter.WriteError` before the error response is actually written.

Added the OnError method to the safehttp.Interceptor interface

---

safehttp/header_test.go
safehttp/incoming_request_test.go
safehttp/mux_test.go
safehttp/plugins/csp/csp_test.go
safehttp/plugins/fetch_metadata/fetch_metadata_test.go
safehttp/response_writer_test.go

Modified the tests that ensure a panic was triggered from
```
defer func() {
if r := recover(); r == nil {
t.Errorf(`... expected panic`)
}
}()
```
to 
```
defer func() {
if r := recover(); r != nil {
return
}
t.Errorf(`... expected panic`)
}()
```
i.e. they now check the `recover()` function recovered from a panic instead of checking it didn't.

Refactor the tests that use the recover() function 

---

safehttp/default_dispatcher.go
safehttp/default_dispatcher_test.go
safehttp/response.go
safehttp/response_writer.go
safehttp/response_writer_test.go
tests/integration/csp/csp_test.go
tests/integration/mux/mux_test.go
tests/integration/safehtml/safehtml_test.go
tests/integration/xsrf/xsrf_test.go

Fixes #150 
Unified the functionality of `WriteJSON`, `ExecuteTemplate` and `Write` inside the new `safehttp.DefaultDispatcher.Write` method, also responsible for setting the `Content-Type` header and writing the status code.

ResponseWriter and Dispatcher now have a single Write method

---

safehttp/plugins/angular_xsrf/angular_xsrf.go
safehttp/plugins/angular_xsrf/angular_xsrf_test.go
safehttp/plugins/csp/csp.go
safehttp/plugins/xsrf/angular/doc.go
safehttp/plugins/xsrf/angular/xsrf.go
safehttp/plugins/xsrf/angular/xsrf_test.go
safehttp/plugins/xsrf/html/doc.go
safehttp/plugins/xsrf/html/xsrf.go
safehttp/plugins/xsrf/html/xsrf_test.go
tests/integration/xsrf/xsrf_test.go

Fixes #194
Created a separate plugin that provides protection against XSRF in Angular. More details can be found here: https://docs.angularjs.org/api/ng/service/$http#cross-site-request-forgery-xsrf-protection
Changed the directory tree to include the two XSRF plugins in the same directory with the functionality used by both placed in a separate file.

XSRF plugin for Angular

---

safehttp/response_writer.go
safehttp/response_writer_test.go

Fixes #151
Previously, there was no way of setting a status code other than `safehttp.NoContent` as the write method in the `safehttp.ResponseWriter` would always set the status code to `safehttp.StatusOK`. Implemented initial functionality and tests to make this possible.

Allow the user to set a custom status code in the safehttp.ResponseWriter

---

safehttp/handler.go
safehttp/interceptor.go
safehttp/mux.go
safehttp/mux_test.go
safehttp/plugins/collector/collector.go
safehttp/plugins/coop/coop.go
safehttp/plugins/cors/cors.go
safehttp/plugins/csp/csp.go
safehttp/plugins/fetch_metadata/fetch_metadata.go
safehttp/plugins/hostcheck/hostcheck.go
safehttp/plugins/hostcheck/hostcheck_test.go
safehttp/plugins/hsts/hsts.go
safehttp/plugins/staticheaders/staticheaders.go
safehttp/plugins/xsrf/angular/xsrf.go
safehttp/plugins/xsrf/html/xsrf.go
safehttp/plugins/xsrf/html/xsrf_test.go
safehttp/response.go
safehttp/response_writer.go
safehttp/response_writer_test.go
safehttp/safehttptest/recorder.go
tests/integration/csp/csp_test.go
tests/integration/header/header_test.go
tests/integration/hsts/hsts_test.go
tests/integration/mux/mux_test.go
tests/integration/safehtml/safehtml_test.go
tests/integration/staticheaders/staticheaders_test.go
tests/integration/xsrf/xsrf_test.go

This is needed for further refactorings of the ResponseWriter where we plan to handle errors due to double-writing, panicking and so on better.

ResponseWriter is now an interface.

---

safehttp/interceptor.go
safehttp/mux_test.go
safehttp/plugins/coop/coop.go
safehttp/plugins/cors/cors.go
safehttp/plugins/csp/csp.go
safehttp/plugins/csp/csp_test.go
safehttp/plugins/fetch_metadata/fetch_metadata.go
safehttp/plugins/hostcheck/hostcheck.go
safehttp/plugins/hsts/hsts.go
safehttp/plugins/staticheaders/staticheaders.go
safehttp/plugins/xsrf/angular/xsrf.go
safehttp/plugins/xsrf/angular/xsrf_test.go
safehttp/plugins/xsrf/html/xsrf.go
safehttp/plugins/xsrf/html/xsrf_test.go
safehttp/response_writer.go

`Commit` and `OnError` interceptor methods can no longer invoke write calls on a `ResponseWriter`. Instead, they receive a `ResponseHeadersWriter` that allows them to modify the HTTP response headers without affecting the control flow. Similarly, they can change the `Response` that's passed to them.
The only way to affect the control flow is for the interceptor to panic, in which case it is treated as an `InternalServerError`.
This introduces a conceptual change in how the framework operates.
1. Once the server has committed to a response (either via `Write` or `WriteError`), no more write operations are allowed. This simplifies further error handling mechanics. Call cycle detection is not needed anymore (e.g. `Write` -> `WriteError` cannot be introduced by user's code).
2. `Commit` and …

Interceptors' `Commit` and `OnError` methods can no longer affect the flow by calling write operations

---

safehttp/flight.go
safehttp/flight_test.go
safehttp/mux_test.go

Previously we were making attempts to recover from some of the panics
and possibly run `OnError` interceptors. This complicates the codebase,
pushes it further from `net/http` behavior and still isn't bulletproof
(what if `OnError` panics?).
In order to prevent from information disclosure, when a panic occurs we
clear all the HTTP response headers. Note that this is only possible if
nothing has been written to the underlying `net/http.ResponseWriter`
yet.
#164, #79
Fixes: #157.

All panics are now propagated to `net/http`.

---

safehttp/default_dispatcher.go
safehttp/dispatcher.go
safehttp/flight.go
safehttp/flight_test.go
safehttp/interceptor.go
safehttp/mux.go
safehttp/mux_test.go
safehttp/plugins/coop/coop.go
safehttp/plugins/cors/cors.go
safehttp/plugins/csp/csp.go
safehttp/plugins/fetch_metadata/fetch_metadata.go
safehttp/plugins/hostcheck/hostcheck.go
safehttp/plugins/hsts/hsts.go
safehttp/plugins/staticheaders/staticheaders.go
safehttp/plugins/xsrf/xsrfangular/xsrf.go
safehttp/plugins/xsrf/xsrfhtml/xsrf.go
safehttp/response.go
safehttp/response_writer.go
safehttp/status.go
tests/integration/errors/errors_test.go

Adding custom error responses to the framework.
1. `ErrorResponse` is now an interface type. `StatusCode` implements it.
2. The `Dispatcher` now implement an `Error` method, accepting an `ErrorResponse` interface object.
3. Error responses written through `safehttp.ResponseWriter.WriteError` now go through the `Commit` phase. This means that `Interceptor.OnError` is not needed anymore.
4. The `ServeMuxConfig.Dispatcher` is now a public field (discovered that it's needed when writing the tests).

Custom error responses

---

safehttp/plugins/csp/csp.go
safehttp/plugins/csp/csp_test.go
tests/integration/csp/csp_test.go

An example server presenting the protection will follow up.
Fixes #99

Add Trusted Types policy to CSP plugin

---

examples/trustedtypes/safe.html
examples/trustedtypes/server.go
examples/trustedtypes/unsafe.html

Add an example of a server which presents DOM XSS protection with Trusted Types.

Add an example of a server which presents DOM XSS protection with Trusted Types

---

safehttp/cookie.go
safehttp/dev.go
safehttp/mux.go
safehttp/plugins/hsts/hsts.go
tests/integration/devmode/devmode_test.go
tests/integration/devmodefreeze/devmodefreeze_test.go

This PR also wires the HSTS plugin and Cookie behavior to disable HTTPS-only behaviors if running in local development mode.
Fixes #171

Add a way to set up the framework in local development mode.

---

safehttp/default_dispatcher.go
safehttp/default_dispatcher_test.go
safehttp/response.go
safehttp/task_test.go

There is currently no way to execute associated templates.
This means loading a directory of templates is impossible, they need to be parsed one by one.
This change makes them available.

Add support for named templates.

---

go.mod
safehttp/fileserver_1_16.go
safehttp/fileserver_1_16_test.go
safehttp/testdata/embed.html

Note that I bumped the go.mod file to use go 1.16 but made sure this
still works with go1.15.
This module will now conditionally build with different features
depending on the compiler version used. Expressing the 1.16 version in
go.mod only means this module *may* use newer features, but it can still
be backward compatible.
This is gonna be useful for any users that want to bundle static resources
in their web servers and doesn't break users on previous versions of Go.

Add support for go1.16 embed.FS.

---

safehttp/defaults/defaults.go
safehttp/fileserver_test.go
safehttp/flight_test.go
safehttp/mux.go
safehttp/mux_test.go
safehttp/plugins/hostcheck/hostcheck_test.go
safehttp/server_test.go
tests/integration/csp/csp_test.go
tests/integration/errors/errors_test.go
tests/integration/header/header_test.go
tests/integration/hsts/hsts_test.go
tests/integration/mux/mux_test.go
tests/integration/safehtml/safehtml_test.go
tests/integration/staticheaders/staticheaders_test.go
tests/integration/xsrf/xsrf_test.go

Linters like https://github.com/bazelbuild/rules_go/blob/master/go/nogo.rst can ban function calls, but not necessarily composite literals / zero value variables of a given type.
In order to make `ServeMuxConfig` creation restricted, it's easier to just hide it behind a function call.
Other benefits:
- prevents changing the `Dispatcher` at runtime
Fixes #269.

ServeMuxConfig needs to be created using NewServeMuxConfig from now on

---

internal/requesttesting/test_harness.go

Fixes #59.
For some reason `server.Shutdown()` waits for quite a bit (~0.5sec) even though everything is closed. Using a forceful `server.Close()` instead.

Speed-up requesttesting test harness

---

internal/requesttesting/headers/host_test.go
internal/requesttesting/headers/statusmessages.go

It is considered poor practice to compare exact error strings,
which causes this test to break on Go1.17.
Fix the test to be more tolerant and work on both Go1.16 and Go1.17.
This test would othewise be broken by https://golang.org/cl/308952.

Fix brittle test

---

safehttp/plugins/xsrf/xsrfhtml/xsrf.go
safehttp/plugins/xsrf/xsrfhtml/xsrf_test.go

Currently we validate CSRF tokens based on paths, but this makes
writing applications very hard.
For example a "logout" button cannot post to a "/logout" endpoint
from a "/profile" page or it will be blocked.
This protection mechanism is aimed at protecting from cross-site
forgery anyways, not cross-path forgery.

xsrfhtml: relax action check to host.

---

examples/sample-application/secure/auth/auth.go
safehttp/flight_test.go
safehttp/interceptor.go
safehttp/mux.go
safehttp/mux_test.go
safehttp/plugins/coop/coop.go
safehttp/plugins/coop/coop_test.go
safehttp/plugins/cors/cors.go
safehttp/plugins/csp/csp.go
safehttp/plugins/fetchmetadata/fetchmetadata.go
safehttp/plugins/fetchmetadata/fetchmetadata_test.go
safehttp/plugins/hostcheck/hostcheck.go
safehttp/plugins/hsts/hsts.go
safehttp/plugins/reportingapi/reporting.go
safehttp/plugins/staticheaders/staticheaders.go
safehttp/plugins/xsrf/xsrfangular/xsrf.go
safehttp/plugins/xsrf/xsrfhtml/xsrf.go
tests/integration/errors/errors_test.go

This makes it possible to have configs live in separate packages from their interceptors, thus empowering us to use simple restrictions rules.
Moreover we had inconsistent disabling mechanisms that didn't force user to attach a reason to them, this PR addresses that too.

Make interceptors match configs instead of configs match interceptors.

---

examples/sample-application/secure/auth/auth.go
examples/sample-application/secure/auth/ctx.go
go.sum
safehttp/flight.go
safehttp/flightvalues_test.go
safehttp/incoming_request.go
safehttp/incoming_request_test.go
safehttp/interceptor.go
safehttp/mux_test.go
safehttp/plugins/csp/csp.go
safehttp/plugins/csp/csp_test.go

Introduces a `safehttp.FlightValues()` function that lets interceptors and handlers refer to a shared state through the `safehttp.IncomingRequest.Context()`.
See `safehttp/flightvalues_test.go` for usage.
Fixes #314.

Interceptors can now carry state throughout the request processing.

---

examples/echo/echo.go
safehttp/defaults/defaults_test.go
safehttp/fileserver.go
safehttp/flightvalues_test.go
safehttp/handler.go
safehttp/handler_test.go
safehttp/incoming_request.go
safehttp/internal/internal.go
safehttp/internal/internal_test.go
safehttp/internals.go
safehttp/plugins/hsts/hsts.go
safehttp/plugins/xsrf/xsrfhtml/xsrf.go
safehttp/restricted/request.go
tests/integration/devmode/devmode_test.go
tests/integration/devmodefreeze/devmodefreeze_test.go
tests/integration/errors/errors_test.go

Notable difference from the `net/http.StripPrefix`: it panics when a prefix cannot be matched. This is clearly a server configuration error.
In order to reduce complexity, the `IncomingRequest.URL` field is no longer there and was replaced by a method. `IncomingRequest` used to contain `req` and `URL` fields, the latter referencing the former. Removing the `URL` field removed the cross-referencing.
Fixes #316.

Provide a StripPrefix utility

---

cmd/bancheck/doc.go
examples/echo/echo.go
safehttp/cookie.go
safehttp/doc.go
safehttp/migration.go
safehttp/mux.go
safehttp/plugins/hsts/hsts.go
safehttp/plugins/staticheaders/staticheaders.go
safesql/safesql.go

Comments are now Markdown-ish. This should fix the issue in #330.

Run gofmt from Go 1.19 over all files

---

examples/echo/echo.go
examples/echo/echo_test.go
examples/echo/security/web/web.go
examples/echo/security/web/web_test.go
examples/sample-application/secure/auth/auth_test.go
examples/sample-application/secure/auth/ctx_test.go
examples/sample-application/secure/dispatcher_test.go
examples/sample-application/secure/mux.go
examples/sample-application/secure/mux_test.go
examples/trustedtypes/server.go
examples/trustedtypes/server_test.go

This PR fixes the examples attached to this project. In particular, inside of them, composite literals were used to create new `ServeMuxConfig` instances instead of passing `nil` to the `NewServeMuxConfig` function. This was causing the applications to panic during the `Mux()` method execution.
In addition, some tests have been introduced in order to be notified in case of future breaks.

Examples fix and tests introduction

---

.github/workflows/main.yaml
cmd/bancheck/config/config_test.go

- use latest Ubuntu instead of ancient 18.04
- use Go 1.20
- remove separate "vet" check. "go test" runs "go vet" as part of the test; enable all vet checks, just to be sure.
Update issue #354
> It's a good idea to open an issue first for discussion.

Attempt to repair Continuous Integration

---

safehttp/server.go

The doc was already referring to this function as onShutdown here https://github.com/google/go-safeweb/blob/master/safehttp/server.go#l=70

fix: renames onshudown to onShutdown
